--- #YAML:1.0
name: Catalyst-Plugin-PageCache
version: 0.03
author:
  - Andy Grundman, C<andy@hybridized.org>
abstract: Cache the output of entire pages
license: perl
generated_by: Module::Build version 0.2604, without YAML.pm
