--- #YAML:1.0
name: Catalyst-Plugin-PageCache
version: 0.14
author:
  - Andy Grundman, <andy@hybridized.org>
abstract: Cache the output of entire pages
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
